version: '3'
services:
  redis:
    image: redislabs/redismod
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    deploy:
      replicas: 1
      
  backend:
    image: ${IMAGE_NAME}/backend:latest
    deploy:
      replicas: 1
    depends_on:
      - redis
    networks:
      - default
      - authenticator-overlay

  server:
    image: ${IMAGE_NAME}/server:latest
    deploy:
      replicas: 1
      labels:
        xyz.tangerie.reverse_proxy.path: "/oauth"
        xyz.tangerie.reverse_proxy.port: "80"
    depends_on:
      - backend
    networks:
      - authenticator-overlay
      - nginx-proxy-overlay

volumes:
  redis-data:
  redis-conf:

networks:
  default:
  authenticator-overlay:
    external: true
    driver: overlay
  nginx-proxy-overlay:
    external: true
    driver: overlay